// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolModel;

#nullable disable

namespace SchoolModel.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("School")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClubStudent", b =>
                {
                    b.Property<int>("ClubsClubId")
                        .HasColumnType("int");

                    b.Property<int>("MembersStudentId")
                        .HasColumnType("int");

                    b.HasKey("ClubsClubId", "MembersStudentId");

                    b.HasIndex("MembersStudentId");

                    b.ToTable("ClubStudent", "School");
                });

            modelBuilder.Entity("SchoolModel.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClubId");

                    b.ToTable("Club", "School");

                    b.HasData(
                        new
                        {
                            ClubId = 101,
                            Name = "STEM"
                        });
                });

            modelBuilder.Entity("SchoolModel.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Course", "School");

                    b.HasData(
                        new
                        {
                            CourseId = 201,
                            Credits = 4,
                            Tag = "ISP-136",
                            Title = "Introduction to C#"
                        },
                        new
                        {
                            CourseId = 202,
                            Credits = 3,
                            Tag = "MTH-200",
                            Title = "Discrete Math"
                        });
                });

            modelBuilder.Entity("SchoolModel.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollment", "School");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 301,
                            CourseId = 201,
                            StudentId = 101
                        },
                        new
                        {
                            EnrollmentId = 302,
                            CourseId = 202,
                            StudentId = 102
                        });
                });

            modelBuilder.Entity("SchoolModel.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("StudentId");

                    b.ToTable("Student", "School");

                    b.HasData(
                        new
                        {
                            StudentId = 101,
                            Email = "ALovelace@reynolds.edu",
                            FirstName = "Ada",
                            LastName = "Lovelace",
                            Major = "Mathematics",
                            PhoneNumber = "804-345-6789"
                        },
                        new
                        {
                            StudentId = 102,
                            Email = "GHopper@reynolds.edu",
                            FirstName = "Grace",
                            LastName = "Hopper",
                            Major = "ITP",
                            PhoneNumber = "804-987-6543"
                        });
                });

            modelBuilder.Entity("SchoolModel.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teacher", "School");

                    b.HasData(
                        new
                        {
                            TeacherId = 101,
                            FullName = "Bob Dust"
                        });
                });

            modelBuilder.Entity("ClubStudent", b =>
                {
                    b.HasOne("SchoolModel.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubsClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolModel.Student", null)
                        .WithMany()
                        .HasForeignKey("MembersStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SchoolModel.Course", b =>
                {
                    b.HasOne("SchoolModel.Teacher", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolModel.Enrollment", b =>
                {
                    b.HasOne("SchoolModel.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolModel.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolModel.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SchoolModel.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SchoolModel.Teacher", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
