#define Part1    // Initial Creation
#define Part2    // Add Email & PhoneNumber to Student
#define Part3    // Add Teacher as 1:M with Course. Add Grade to Enrollment
#define Part4    // Add Club as M:M with Student
// Do not define ALL of Part5, Part6, and Part7. Each is Exclusive of the others //
//#define Part5    // Unit Testing GPA 0
//#define Part6    // Unit Testing GPA Null
#define Part7    // Unit Testing for Weighted GPA
/*
    Install the following libraries. Use Version 8.0.0 (not latest):
• 	Microsoft.EntityFrameworkCare
• 	Microsoft.EntityFrameworkCore.SqlServer
• 	Microsoft.EntityFrameworkCore.Tools
    These allow migrations to run and SQL Server to be used.  
*/
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Reflection.Emit;



namespace SchoolModel
{
    public class SchoolContext : DbContext
    {
        // Change the declaration of _loggerFactory to nullable to resolve CS8618
        private readonly ILoggerFactory? _loggerFactory;

        public SchoolContext(DbContextOptions<SchoolContext> options)
            : base(options) { }

        public DbSet<Student> Students => Set<Student>();
        public DbSet<Course> Courses => Set<Course>();
        public DbSet<Enrollment> Enrollments => Set<Enrollment>();
#if Part3
        public DbSet<Teacher> Teachers { get; set; }
#endif
#if Part4
        public DbSet<Club> Clubs { get; set; }
#endif 

        public SchoolContext(DbContextOptions<SchoolContext> options, ILoggerFactory loggerFactory)
        : base(options)
        {
            _loggerFactory = loggerFactory;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseLoggerFactory(_loggerFactory);
            optionsBuilder.EnableSensitiveDataLogging();   // optional but helpful
        }


        // <---- Cascade Delete ----> //
        /*
            In EF Core, many‑to‑many join tables are dependent-only entities.
            Dependent entities get cascade delete by default.
            So yes — deleting a parent automatically cleans up the join rows.
        */
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("School");

            modelBuilder.Entity<Enrollment>()
                .HasOne(e => e.Student)
                .WithMany(s => s.Enrollments)
                .HasForeignKey(e => e.StudentId);

            modelBuilder.Entity<Enrollment>()
                .HasOne(e => e.Course)
                .WithMany(c => c.Enrollments)
                .HasForeignKey(e => e.CourseId);

            /*
             * Note that EF Core makes "ID" columns as Identity columns
             * But when Inserting data, turns "Identity Insert" on so explicit PK values must be set.
             * EF Core needs a stable, known primary key value so it can:
                - insert the row during the migration
                - update the row if the seed changes
                - delete the row if the seed is removed
              * EF Core cannot rely on auto‑generated Identity values for this, because Identity values are:
                - generated by SQL Server
                - not known ahead of time
                - not guaranteed to be the same on every machine
            */
            modelBuilder.Entity<Student>().HasData(
                    new Student
                    {
                        StudentId = 101
                        ,
                        FirstName = "Ada"
                        ,
                        LastName = "Lovelace"
                        ,
                        Major = "Mathematics"
#if Part2
                        ,
                        Email = "ALovelace@reynolds.edu"       //--< Add Email to Seed Data <<<
                        ,
                        PhoneNumber = "804-345-6789"
#endif
                    },
                    new Student
                    {
                        StudentId = 102
                        ,
                        FirstName = "Grace"
                        ,
                        LastName = "Hopper"
                        ,
                        Major = "ITP"
#if Part2
                        ,
                        Email = "GHopper@reynolds.edu"          //--< Add Email to Seed Data <<<
                        ,
                        PhoneNumber = "804-987-6543"
#endif
                    }       //--< Add Email to Seed Data <<<
                );

            modelBuilder.Entity<Course>().HasData(
                new Course { CourseId = 201, Tag = "ISP-136", Title = "Introduction to C#", Credits = 4 },
                new Course { CourseId = 202, Tag = "MTH-200", Title = "Discrete Math", Credits = 3 }
            );

            modelBuilder.Entity<Enrollment>().HasData(
                new Enrollment { EnrollmentId = 301, StudentId = 101, CourseId = 201 },
                new Enrollment { EnrollmentId = 302, StudentId = 102, CourseId = 202 }
            );
#if Part3
            modelBuilder.Entity<Teacher>().HasData(
                new Teacher { TeacherId = 101, FullName = "Bob Dust" }
            );
#endif
#if Part4
            modelBuilder.Entity<Club>().HasData(
                new Club { ClubId = 101, Name = "STEM" }
            );
#endif
        }
    }


    [Table("Student")]
    public class Student
    {
        public int StudentId { get; set; }

        public required string FirstName { get; set; }
        public required string LastName { get; set; }

        public string? Major { get; set; }
#if Part2
        /// <summary>
        /// Gets or sets the email address. This is added AFTER the initial build
        /// </summary>
        public string? Email { get; set; }

        [MaxLength(15)]
        /// <summary>
        /// Gets or sets the phone number associated with the entity. This too is added AFTER the initial build.
        /// Migration looks like this afterwards:
        ///  migrationBuilder.AddColumn<string>(
        ///  name: "PhoneNumber",
        ///        schema: "School",
        ///        table: "Student",
        ///        type: "nvarchar(15)",
        ///        nullable: true,
        ///        defaultValue: "");
        /// </summary>
        public string? PhoneNumber { get; set; }
#endif
        /// <summary>
        /// Gets or sets the collection of enrollments associated with the Student.
        /// A Student can have Many Enrollments--Can be enrolled in many courses
        /// </summary>
        public List<Enrollment> Enrollments { get; set; } = new();
#if Part4
        /// <summary>
        /// Gets or sets the collection of clubs that a Student belongs to.  Added new AFTER the initial build.
        /// </summary>
        public List<Club> Clubs { get; set; } = new();
#endif
#if Part5
        [NotMapped]             //--< Does not store this in the DB <<<
        public double? GPA =>
            Enrollments
                .Where(e => e.GradePoints.HasValue)
                .Select(e => e.GradePoints!.Value)
                .DefaultIfEmpty()
                .Average();
#endif
#if Part6
        [NotMapped]             //--< Does not store this in the DB <<<
        public double? GPA
        {
            get
            {
                var gradePoints = Enrollments
                    .Where(e => e.GradePoints.HasValue)
                    .Select(e => e.GradePoints!.Value)
                    .ToList();

                return gradePoints.Count == 0
                    ? null
                    : gradePoints.Average();
            }
        }
#endif
#if Part7
[NotMapped]
public double? GPA
{
    get
    {
        var graded = Enrollments
            .Where(e => e.GradePoints.HasValue && e.Course != null)
            .Select(e => new
            {
                Points = e.GradePoints!.Value,
                Credits = e.Course.Credits
            })
            .ToList();

        if (graded.Count == 0)
            return null;

        double totalPoints = graded.Sum(g => g.Points * g.Credits);
        double totalCredits = graded.Sum(g => g.Credits);

        return totalPoints / totalCredits;
    }
}
        [NotMapped]
        public int EnrollmentCount => Enrollments.Count;
#endif
        /// <summary>
        /// Uses LINQ to get the full name, consisting of the first name followed by the last name.
        /// </summary>
        public string FullName => $"{FirstName} {LastName}";
    }

    [Table("Course")]
    public class Course
    {
        public int CourseId { get; set; }

        public required string Tag { get; set; }
        public required string Title { get; set; }
#if Part3
        /// <summary>
        /// Gets or sets the unique identifier of the teacher. Added AFTER the initial build. This is a new 1:M relationship
        /// </summary>
        public int? TeacherId { get; set; }
        /// <summary>
        /// Teacher for the course. Added AFTER the initial build
        /// </summary>
        public Teacher? Teacher { get; set; }
#endif

        public int Credits { get; set; }
        /// <summary>
        /// Gets or sets the collection of enrollments associated with the Course.
        /// A Course can have Many Enrollments--Can have many Students enrolled in the course.
        /// </summary>
        public List<Enrollment> Enrollments { get; set; } = new();
        [NotMapped]
        public int EnrollmentCount => Enrollments.Count;
    }
    /// <summary>
    /// Represents one student's enrollment in one course, including grade and related entities.
    /// </summary>
    /// <remarks>Includes navigation properties to the associated student and course.</remarks>
    [Table("Enrollment")]
    public class Enrollment
    {
        public int EnrollmentId { get; set; }

        public int StudentId { get; set; }
        public Student Student { get; set; } = null!;


        public int CourseId { get; set; }
        public Course Course { get; set; } = null!;

#if Part3
        public string? Grade { get; set; }

        public double? GradePoints =>
            Grade switch
            {
                "A" => 4.0,
                "B" => 3.0,
                "C" => 2.0,
                "D" => 1.0,
                "F" => 0.0,
                _ => null
            };
#endif
    }
#if Part3
    /// <summary>
    /// Represents a teacher with an identifier, full name, and associated courses. Teacher : Course = 1:M Relationship
    /// </summary>
    [Table("Teacher")]
    public class Teacher
    {
        public int TeacherId { get; set; }
        [Required]
        public string FullName { get; set; } = string.Empty;

        public List<Course> Courses { get; set; } = new();
    }
#endif
#if Part4
    [Table("Club")]
    public class Club
    {
        public int ClubId { get; set; }
        public string Name { get; set; } = string.Empty;

        public List<Student> Members { get; set; } = new();
    }
#endif
}