// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetParkModel;

#nullable disable

namespace PetParkModel.Migrations
{
    [DbContext(typeof(PetParkContext))]
    [Migration("20260428145115_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PetPark")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetParkModel.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PetId");

                    b.ToTable("Pets", "PetPark");

                    b.HasData(
                        new
                        {
                            PetId = 1,
                            Name = "Buddy",
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 2,
                            Name = "Luna",
                            Species = "Cat"
                        });
                });

            modelBuilder.Entity("PetParkModel.Trick", b =>
                {
                    b.Property<int>("TrickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrickId"));

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrickId");

                    b.ToTable("Tricks", "PetPark");

                    b.HasData(
                        new
                        {
                            TrickId = 1,
                            DifficultyLevel = "Easy",
                            Name = "Sit"
                        },
                        new
                        {
                            TrickId = 2,
                            DifficultyLevel = "Medium",
                            Name = "Roll Over"
                        });
                });

            modelBuilder.Entity("PetTrick", b =>
                {
                    b.Property<int>("PetsPetId")
                        .HasColumnType("int");

                    b.Property<int>("TricksTrickId")
                        .HasColumnType("int");

                    b.HasKey("PetsPetId", "TricksTrickId");

                    b.HasIndex("TricksTrickId");

                    b.ToTable("PetTrick", "PetPark");

                    b.HasData(
                        new
                        {
                            PetsPetId = 1,
                            TricksTrickId = 1
                        },
                        new
                        {
                            PetsPetId = 1,
                            TricksTrickId = 2
                        },
                        new
                        {
                            PetsPetId = 2,
                            TricksTrickId = 1
                        });
                });

            modelBuilder.Entity("PetTrick", b =>
                {
                    b.HasOne("PetParkModel.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetsPetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetParkModel.Trick", null)
                        .WithMany()
                        .HasForeignKey("TricksTrickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
