// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetParkModel;

#nullable disable

namespace PetParkModel.Migrations
{
    [DbContext(typeof(PetParkContext))]
    [Migration("20260428175453_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PetPark")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetParkModel.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners", "PetPark");

                    b.HasData(
                        new
                        {
                            OwnerId = 1,
                            FullName = "Alex Carter"
                        },
                        new
                        {
                            OwnerId = 2,
                            FullName = "Jordan Blake"
                        },
                        new
                        {
                            OwnerId = 3,
                            FullName = "Taylor Morgan"
                        });
                });

            modelBuilder.Entity("PetParkModel.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PetId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PetId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets", "PetPark");

                    b.HasData(
                        new
                        {
                            PetId = 1,
                            Name = "Buddy",
                            OwnerId = 1,
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 2,
                            Name = "Luna",
                            OwnerId = 2,
                            Species = "Cat"
                        },
                        new
                        {
                            PetId = 10,
                            Name = "Mango",
                            OwnerId = 1,
                            Species = "Parrot"
                        },
                        new
                        {
                            PetId = 11,
                            Name = "Shadow",
                            OwnerId = 3,
                            Species = "Dog"
                        },
                        new
                        {
                            PetId = 12,
                            Name = "Cleo",
                            OwnerId = 2,
                            Species = "Rabbit"
                        });
                });

            modelBuilder.Entity("PetParkModel.PetTreat", b =>
                {
                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("TreatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateGiven")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("PetId", "TreatId");

                    b.HasIndex("TreatId");

                    b.ToTable("PetTreats", "PetPark");

                    b.HasData(
                        new
                        {
                            PetId = 1,
                            TreatId = 1,
                            DateGiven = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 2
                        },
                        new
                        {
                            PetId = 2,
                            TreatId = 2,
                            DateGiven = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 1
                        },
                        new
                        {
                            PetId = 10,
                            TreatId = 3,
                            DateGiven = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 3
                        },
                        new
                        {
                            PetId = 11,
                            TreatId = 1,
                            DateGiven = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 1
                        },
                        new
                        {
                            PetId = 12,
                            TreatId = 3,
                            DateGiven = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("PetParkModel.Treat", b =>
                {
                    b.Property<int>("TreatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreatId"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("TreatId");

                    b.ToTable("Treats", "PetPark");

                    b.HasData(
                        new
                        {
                            TreatId = 1,
                            Calories = 40,
                            Name = "Peanut Biscuit"
                        },
                        new
                        {
                            TreatId = 2,
                            Calories = 30,
                            Name = "Salmon Bite"
                        },
                        new
                        {
                            TreatId = 3,
                            Calories = 10,
                            Name = "Carrot Chip"
                        });
                });

            modelBuilder.Entity("PetParkModel.Trick", b =>
                {
                    b.Property<int>("TrickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrickId"));

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrickId");

                    b.ToTable("Tricks", "PetPark");

                    b.HasData(
                        new
                        {
                            TrickId = 1,
                            DifficultyLevel = "Easy",
                            Name = "Sit"
                        },
                        new
                        {
                            TrickId = 2,
                            DifficultyLevel = "Medium",
                            Name = "Roll Over"
                        },
                        new
                        {
                            TrickId = 10,
                            DifficultyLevel = "Easy",
                            Name = "Shake"
                        },
                        new
                        {
                            TrickId = 11,
                            DifficultyLevel = "Hard",
                            Name = "Play Dead"
                        },
                        new
                        {
                            TrickId = 12,
                            DifficultyLevel = "Medium",
                            Name = "Fetch"
                        });
                });

            modelBuilder.Entity("PetTrick", b =>
                {
                    b.Property<int>("PetsPetId")
                        .HasColumnType("int");

                    b.Property<int>("TricksTrickId")
                        .HasColumnType("int");

                    b.HasKey("PetsPetId", "TricksTrickId");

                    b.HasIndex("TricksTrickId");

                    b.ToTable("PetTrick", "PetPark");

                    b.HasData(
                        new
                        {
                            PetsPetId = 1,
                            TricksTrickId = 1
                        },
                        new
                        {
                            PetsPetId = 1,
                            TricksTrickId = 2
                        },
                        new
                        {
                            PetsPetId = 1,
                            TricksTrickId = 12
                        },
                        new
                        {
                            PetsPetId = 2,
                            TricksTrickId = 1
                        },
                        new
                        {
                            PetsPetId = 2,
                            TricksTrickId = 10
                        },
                        new
                        {
                            PetsPetId = 10,
                            TricksTrickId = 10
                        },
                        new
                        {
                            PetsPetId = 11,
                            TricksTrickId = 1
                        },
                        new
                        {
                            PetsPetId = 11,
                            TricksTrickId = 11
                        },
                        new
                        {
                            PetsPetId = 11,
                            TricksTrickId = 12
                        },
                        new
                        {
                            PetsPetId = 12,
                            TricksTrickId = 2
                        });
                });

            modelBuilder.Entity("PetParkModel.Pet", b =>
                {
                    b.HasOne("PetParkModel.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PetParkModel.PetTreat", b =>
                {
                    b.HasOne("PetParkModel.Pet", "Pet")
                        .WithMany("PetTreats")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetParkModel.Treat", "Treat")
                        .WithMany("PetTreats")
                        .HasForeignKey("TreatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Treat");
                });

            modelBuilder.Entity("PetTrick", b =>
                {
                    b.HasOne("PetParkModel.Pet", null)
                        .WithMany()
                        .HasForeignKey("PetsPetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetParkModel.Trick", null)
                        .WithMany()
                        .HasForeignKey("TricksTrickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetParkModel.Owner", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetParkModel.Pet", b =>
                {
                    b.Navigation("PetTreats");
                });

            modelBuilder.Entity("PetParkModel.Treat", b =>
                {
                    b.Navigation("PetTreats");
                });
#pragma warning restore 612, 618
        }
    }
}
